version: '3.8'

services:
  stock-image-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - elasticsearch
    volumes:
      - .:/app
      - ./logs:/src/logs
    command: bun run index.ts --watch --hot | pino-pretty
  
  elasticsearch:
    image: elasticsearch:8.15.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.enable=all
      - cluster.routing.allocation.node_concurrent_recoveries=2
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false

  kibana:
    image: kibana:8.15.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build:
        context: ./filebeat
    command: filebeat -e -strict.perms=false
    volumes:
        - ./logs:/src/logs
    depends_on:
        - elasticsearch
        - kibana
