version: '3.8'

services:
  hono-server:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - .:/app
    command: bun run index.ts --watch --hot | pino-pretty