name: Fetchpix Docker Image CI/CD Pipeline

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.12

      - name: Install dependencies
        run: bun install

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/fetchpix:latest

      - name: Push the Docker image to the registry
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fetchpix:latest

      - name: Run API server
        run: screen -d -m bun run start

      - name: Run tests
        run: bun run test

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fetchpix:latest
      - name: Rollback on failure
        if: failure()
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/fetchpix:latest fetchpix:$(date +%s)
          docker push ${{ secrets.DOCKER_USERNAME }}/fetchpix:latest
